version: "3.9"
services:
  backend:
    hostname: backendjs
    container_name: backendjs
    restart: on-failure
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      PORT: 8000
      DB: "mongodb://root:globant@pg-db:27017/"
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
     - backend
     - frontend 
  db: 
    image: mongo
    hostname: mongodb
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: globant
    ports:
      - '27017:27017'
    networks:
      - backend
  frontend:
    hostname: frontendjs
    container_name: frontendjs
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend  
    networks:
      - frontend
networks:
  frontend:
  backend:
